# Generated by Django 3.1 on 2020-09-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0002_userconnection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userconnection',
            unique_together={('creator', 'following')},
        ),
    ]
